### PR TITLE
added support for kustomization.yml

### PR DESCRIPTION
**Pull request by surajkrishan**
**What issue type does this pull request address?** (keep at least one, remove the others) 
/kind bugfix

image

**What does this pull request do? Which issues does it resolve?** (use `resolves #<issue_number>` if possible) 
resolves #

N/A

**Please provide a short message that should be published in the DevSpace release notes**
Fixed an issue where DevSpace check for only kustomization.yaml extension 

**What else do we need to know?** 
added support for kustomization.yml extension as well.

### CODE REVIEW

**Comment by surajkrishan** [comment]
Hi @FabianKramm / @LukasGentele  - could you plz help in reviewing the PR.

**Review by lizardruss — APPROVED** [review]
LGTM

**Comment by lizardruss** [comment]
@surajkrishan Looks like there were some linting & e2e test failures. Would you mind taking a look?

**Comment by surajkrishan** [comment]
> @surajkrishan Looks like there were some linting & e2e test failures. Would you mind taking a look?

sure checking!

**Review by lizardruss — APPROVED** [review]
LGTM

**Pull request merged**
