### PR TITLE
docs: move is_dependency to correct function group

### PR DESCRIPTION
**Pull request by jackwilsdon**
**What issue type does this pull request address?** (keep at least one, remove the others) 
/kind documentation

**What does this pull request do? Which issues does it resolve?** (use `resolves #<issue_number>` if possible) 
Moves `is_dependency` from the "Global Functions" section of the [built-in functions list](http://localhost:8000/docs/configuration/functions/#built-in-functions) to the "Pipeline-Only Functions" section (`is_dependency` is pipeline-only).

**Please provide a short message that should be published in the DevSpace release notes**
Updated classification of `is_dependency` in documentation.

### CODE REVIEW

**Review by lizardruss — CHANGES_REQUESTED** [review]
@jackwilsdon

Thanks for the PR!

It looks like there are some issues with our [function partials generation script](https://github.com/devspace-sh/devspace/blob/main/docs/hack/functions/main.go). The first being that it's not included in [gendocs.sh](https://github.com/devspace-sh/devspace/blob/main/gendocs.sh). The second is that it's not placing these in the correct category.

If you get a chance to look into those issues, that would be great! Otherwise I can take a look soon.

**Comment by lizardruss** [comment]
@jackwilsdon Thank you so much! Yeah I think including it in this PR would be good. Adding `is_in` should be pretty straightforward. I'm just learning that the [text for that documentation is here](https://github.com/devspace-sh/devspace/blob/b5314931131d2feb6d4d231c2d7db85838289e8a/docs/hack/functions/main.go#L231-L433), and looks like it was updated but the partial generation was never run afterwards. Looks like `is_dependency` can be moved to the correct group by removing [this flag](https://github.com/devspace-sh/devspace/blob/b5314931131d2feb6d4d231c2d7db85838289e8a/docs/hack/functions/main.go#L318).

You've probably figured all this out, but I'm also just learning about this part of the document generation code 👍

**Comment by jackwilsdon** [comment]
I've updated this PR to include the changes discussed :+1:

**Review by FabianKramm — APPROVED** [review]
@jackwilsdon thanks a lot for the PR! LGTM!

**Review by lizardruss — APPROVED** [review]

**Pull request merged**
