### PR TITLE
updateImageTags actually defaults to true

### PR DESCRIPTION
**Pull request by opticoder**
**What issue type does this pull request address?** (keep at least one, remove the others) 
/kind bugfix
/kind documentation

**What does this pull request do? Which issues does it resolve?** (use `resolves #<issue_number>` if possible) 
fix wrong updateImageTags default value mention in docs

**Please provide a short message that should be published in the DevSpace release notes**
fix updateImageTags default value mention in docs

**What else do we need to know?**

### CODE REVIEW

**Comment by FabianKramm** [comment]
@opticoder thanks for the PR! It actually defaults to `true`, so in the docs its actually correct

**Comment by opticoder** [comment]
@FabianKramm Thanks for the quick reply! But doesn't it mean then here https://www.devspace.sh/docs/configuration/deployments/#deployments-updateImageTags default value is not correct? And if yes, should I change the PR or create a new one?

**Comment by FabianKramm** [comment]
@opticoder oh yes! You are correct its actually wrong in the other place!

**Comment by opticoder** [comment]
updated the fix for default to true

**Comment by lizardruss** [comment]
Closing in favor of #2714, since there were fixes to the documentation generation code needed to avoid overwriting this change.

**Pull request closed without merging**
